accounts/urls.py
# accounts/urls.py
from django.urls import path
from .views import register, login_view
from django.contrib.auth import views as auth_logout

app_name = 'accounts'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', auth_logout.LogoutView.as_view(), name='logout'),
]

core/urls.py
from django.urls import path
from .views import homepage

urlpatterns = [
    path('', homepage, name="HomePage"),
]

defenserai/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('',include("core.urls")),
    path('data_capture/', include("data_capture.urls", namespace='data_capture')),
    path('management/', include("management.urls", namespace='management')),
    path('data_storage/', include("data_storage.urls", namespace='data_storage')),
    path('alerts/', include("alerts.urls", namespace='alerts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

def homepage(request):
    
    return render(request, 'index.html', {'user': request.user})

    

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Estilos generales del navbar que se aplicarán a todas las apps -->
    <link href="{% static 'core/css/tailwind.css' %}" rel="stylesheet"> 
    <link href="{% static 'core/css/style.css' %}" rel="stylesheet"> 
    <link rel="icon" href="{% static 'core/images/logo defenserai.png' %}" type="image/x-icon">
    
    <!--fuentes-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- Espacio para sobreescribir estilos de cada app -->
    {% block styles %}
    {% endblock %}      

    <title>{% block title %}base{% endblock %}</title>
</head>

<body>

<header class="bg-[#1F233E] relative font-poppins">
  <div class="container mx-auto">
      <nav class="flex items-center justify-between py-4">
          <a class="navbar-brand flex items-center" href="{% url 'HomePage' %}">
              <div class="logo_box">
                  <img class="w-24" src="{% static 'core/images/logo defenserai.png' %}" alt="Logo" />
              </div>
              {% if user.is_authenticated %}
              <span class="text-white font-bold ml-3">Bienvenido, {{ user.username }}</span>
              {% endif %}
          </a>

          <button id="menu-btn" class="text-white hover:text-blue-300 block md:hidden">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7" />
              </svg>
          </button>
 
          <div class="hidden md:flex items-center space-x-6" id="menu">
              <ul class="flex items-center space-x-6 text-white">
                  <li class="nav-item">
                      <a class="nav-link hover:text-blue-300" href="{% url 'HomePage' %}">Home</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link hover:text-blue-300" href="">Nosotros</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link hover:text-blue-300" href="">Contacto</a>
                  </li>
                  {% if not user.is_authenticated %}
                  <li class="nav-item">
                      <a class="nav-link hover:text-blue-300" href="{% url 'accounts:login' %}">Iniciar sesión</a>
                  </li>
                  {% else %}
                  <li>
                      <form method="post" action="{% url 'accounts:logout' %}">
                          {% csrf_token %}
                          <button class="hover:text-blue-300">Cerrar sesión</button>
                      </form>
                  </li>
                  {% endif %}
              </ul>
              <form class="flex items-center" id="search-form">
                  <input id="search-input" class="hidden transition-all duration-500 ease-in-out border border-gray-300 rounded px-2 py-1 w-32" type="search" placeholder="Search" aria-label="Search" />
                  <button id="search-btn" class="text-white hover:text-blue-300 ml-2" type="button">
                      <img src="{% static 'core/images/search-icon.png' %}" class="h-6 w-6">
                      </img>
                  </button>
              </form>
          </div>
      </nav>

      <!-- Menú desplegable para pantallas pequeñas -->
      <div id="mobile-menu" class="hidden bg-[#1F233E] p-4 absolute top-full left-0 right-0">
          <ul class="flex flex-col space-y-2 text-white">
              <li class="nav-item">
                  <a class="nav-link hover:text-blue-300" href="{% url 'HomePage' %}">Home</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link hover:text-blue-300" href="">Nosotros</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link hover:text-blue-300" href="">Contacto</a>
              </li>
              {% if not user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link hover:text-blue-300" href="{% url 'accounts:login' %}">Login</a>
              </li>
              {% else %}
              <li>
                  <form method="post" action="{% url 'accounts:logout' %}">
                      {% csrf_token %}
                      <button class="hover:text-blue-300">Cerrar sesión</button>
                  </form>
              </li>
              {% endif %}
          </ul>
          <form class="flex items-center mt-4">
              <input id="search-input-mobile" class="border border-gray-300 rounded px-2 py-1 w-full" type="search" placeholder="Search" aria-label="Search" />
              <button id="search-btn-mobile" class="text-white hover:text-blue-300 ml-2" type="button">
                  <img src="{% static 'core/images/search-icon.png' %}" class="h-6 w-6">
                  </img>
              </button>
          </form>
      </div>
  </div>
</header>


    <!-- Bloque de contenido -->
    {% block content %}
    {% endblock %}

    <script src="{% static 'core/js/navbar.js' %}"></script>
    <style>
      @media (max-width: 767px) {
          #menu {
              display: none;
          }
      }
    </style>

    
</body>

</html>

{% block scripts %}
    <script src="{% static 'data_storage/js/modal.js' %}"></script>
{% endblock %}