core/urls.py
from django.urls import path
from .views import homepage

urlpatterns = [
    path('', homepage, name="HomePage"),
]

data_storage/urls.py
from django.urls import path
from .views import (
    main,
    generar_informe,
    lista_reportes,
    eliminar_alerta,
    eliminar_reporte,
)

app_name = "data_storage"

urlpatterns = [
    path("main/", main, name="main"),
    path("reports/", lista_reportes, name="reports"),
    path("generar_informe/", generar_informe, name="generar_informe"),
    path("eliminar_alerta/<int:alerta_id>/", eliminar_alerta, name="eliminar_alerta"),
    path("eliminar_reporte/<int:reporte_id>/", eliminar_reporte, name="eliminar_reporte"),
]

defenserai/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('',include("core.urls")),
    path('data_capture/', include("data_capture.urls", namespace='data_capture')),
    path('management/', include("management.urls", namespace='management')),
    path('data_storage/', include("data_storage.urls", namespace='data_storage')),
    path('alerts/', include("alerts.urls", namespace='alerts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data_storage/models.py
from django.db import models
from django.db import models


class Report(models.Model):
    name = models.CharField(max_length=100)
    generated_at = models.DateTimeField(auto_now_add=True)
    pdf_file = models.FileField(upload_to='reports/')
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Reporte: {self.name} - {self.generated_at.strftime('%Y-%m-%d %H:%M')}"

data_storage/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.files.base import ContentFile
from django.contrib.auth.decorators import login_required, permission_required
from alerts.models import Alert
from io import BytesIO
from reportlab.pdfgen import canvas
import calendar
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from .models import Report
from datetime import datetime
from django.shortcuts import get_object_or_404, redirect
from .models import Report

@login_required(login_url="accounts:login")
def main(request):
    alert_number = request.GET.get("alert_number")
    anomaly_type = request.GET.get("anomaly_type")
    confidence = request.GET.get("confidence")
    alert_date = request.GET.get("alert_date")

    alertas = Alert.objects.values(
        "id",
        "anomaly_type",
        "confidence",
        "frame_image",
        "timestamp",
        "created_by__username",
    )

    delete_alert = request.user.has_perm('alerts.delete_alert')
    view_alert = request.user.has_perm('alerts.view_alert')
    view_report = request.user.has_perm('data_storage.view_report')
    permissions = {
        'delete_alert' : delete_alert,
        'view_alert' : view_alert,
        'view_report' : view_report,
    }

    if alert_number:
        alertas = alertas.filter(id=alert_number)
    if anomaly_type:
        alertas = alertas.filter(anomaly_type__icontains=anomaly_type)
    if confidence:
        try:
            confidence_float = float(confidence)
            alertas = alertas.filter(confidence__gte=confidence_float / 100)
        except ValueError:
            pass
    if alert_date:
        alertas = alertas.filter(timestamp__date=alert_date)

    alertas_dict = list(alertas)
    for alerta in alertas_dict:
        alerta["confidence"] = int(round(alerta["confidence"] * 100, 2))

    return render(request, "data_storage/main.html", {"alertas_dict": alertas_dict, 'permissions': permissions})


@login_required(login_url="accounts:login")
def generar_informe(request):
    mes = int(request.POST.get("mes", 1))
    anio = int(request.POST.get("anio", 1))
    alertas = Alert.objects.filter(timestamp__year=anio, timestamp__month=mes)

    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    p.setFont("Helvetica-Bold", 16)
    p.drawString(
        100, height - 80, f"Informe de Alertas - {calendar.month_name[mes]} {anio}"
    )
    p.setFont("Helvetica", 10)
    p.drawString(
        100,
        height - 100,
        "Este informe contiene un resumen detallado de las alertas registradas durante el mes seleccionado.",
    )
    p.drawString(
        100,
        height - 115,
        "A continuación, se listan los eventos capturados por el sistema de vigilancia en tiempo real.",
    )
    p.line(100, height - 130, width - 100, height - 130)

    y_position = height - 150
    for alerta in alertas:
        if y_position < 100:
            p.showPage()
            y_position = height - 100

        p.setFont("Helvetica-Bold", 12)
        p.setFillColor(colors.darkblue)
        p.drawString(100, y_position, f"Alerta ID: {alerta.id} - {alerta.anomaly_type}")
        y_position -= 15

        p.setFont("Helvetica", 10)
        p.setFillColor(colors.black)
        p.drawString(120, y_position, f"Confianza: {alerta.confidence * 100:.2f}%")
        y_position -= 15
        p.drawString(
            120,
            y_position,
            f"Fecha de Captura: {alerta.timestamp.strftime('%d/%m/%Y %H:%M:%S')}",
        )
        y_position -= 15
        p.drawString(
            120,
            y_position,
            f"Creado por: {alerta.created_by.username if alerta.created_by else 'Desconocido'}",
        )
        y_position -= 260

        if alerta.frame_image:
            image_path = alerta.frame_image.path
            try:

                image_height = 250
                image_width = 400
                p.drawImage(
                    image_path, 100, y_position, width=image_width, height=image_height
                )
            except Exception as e:
                print(f"Error al agregar la imagen de la alerta {alerta.id}: {e}")

        y_position -= 20

    p.showPage()
    p.save()

    buffer.seek(0)
    pdf_data = buffer.getvalue()

    report = Report(
        name=f"Informe de Alertas - {calendar.month_name[mes]} {anio}",
        description="Informe mensual detallado de alertas registradas en el sistema.",
        generated_at=datetime.now(),
    )
    report.pdf_file.save(f"informe_alertas_{mes}_{anio}.pdf", ContentFile(pdf_data))
    report.save()

    return HttpResponse(pdf_data, content_type="application/pdf")


@login_required(login_url="accounts:login")
def eliminar_alerta(request, alerta_id):
    alerta = get_object_or_404(Alert, id=alerta_id)
    alerta.delete()

    return redirect("data_storage:main")


def eliminar_reporte(request, reporte_id):
    reporte = get_object_or_404(Report, id=reporte_id)
    reporte.delete()
    return redirect("data_storage:reports")

@permission_required('data_storage.view_report', login_url='data_storage:main')
@login_required(login_url="accounts:login")
def lista_reportes(request):
    informes = Report.objects.all().order_by("-generated_at")
    delete_report = request.user.has_perm('data_storage.delete_report')
    permissions = {
        'delete_report' : delete_report,
    }
    return render(request, "data_storage/reports.html", {"informes": informes, 'permissions': permissions})

data_storage/templates/data_storage/main.html
{% extends 'core/base.html' %} 
{% load static %}

{% block styles %}   
  <link href="{% static 'data_storage/css/tailwind.css' %}" rel="stylesheet"> 
  <link href="{% static 'data_storage/css/style.css' %}" rel="stylesheet"> 
{% endblock %}

{% block title %}Almacenamiento y reportes{% endblock %}

{% block content %}
<div class="border-1 border-gray-300 p-3 shadow-lg my-4 font-poppins">
    <div class="flex justify-between">
    <h1 class="text-3xl font-bold text-center leading-loose mx-4">Registro de alertas</h1>
    {% if permissions.view_report %}
    <a href="../reports">
        <button class="text-3xl font-medium text-center leading-loose mx-4 text-black 
                       hover:text-blue-500 transition duration-300">
            Ir a reportes
        </button>
    </a>
    {% endif %}
    </div>
</div>


<div class="mx-4 font-poppins">
    <form method="GET" action="" class="mb-4">
        <div class="flex space-x-4">
            <div class="flex-1">
                <label for="alert_number" class="block text-lg font-medium text-gray-700">Filtrar por número de alerta:</label>
                <input type="number" name="alert_number" id="alert_number" value="{{ request.GET.alert_number }}" class="mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 text-lg">
            </div>
            <div class="flex-1">
                <label for="anomaly_type" class="block text-lg font-medium text-gray-700">Filtrar por palabra clave:</label>
                <input type="text" name="anomaly_type" id="anomaly_type" value="{{ request.GET.anomaly_type }}" class="mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 text-lg">
            </div>
            <div class="flex-1">
                <label for="confidence" class="block text-lg font-medium text-gray-700">Confiabilidad:</label>
                <select name="confidence" id="confidence" class="mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 text-lg">
                    <option value="">Mayor al:</option>
                    <option value="50">50%</option>
                    <option value="60">60%</option>
                    <option value="70">70%</option>
                    <option value="80">80%</option>
                    <option value="90">90%</option>
                </select>
            </div>
            <div class="flex-1">
                <label for="alert_date" class="block text-lg font-medium text-gray-700">Filtrar por fecha:</label>
                <input type="date" name="alert_date" id="alert_date" value="{{ request.GET.alert_date }}" class="mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 text-lg">
            </div>
            <div class="flex items-end ml-medium">
                <button type="submit" class="bg-blue-500 text-white p-2 rounded-md hover:bg-blue-600 text-lg">Enviar</button>
            </div>
        </div>
    </form>
</div>


<div class="mx-4 font-poppins">
    <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
            <tr>
                <th scope="col" class="px-6 py-3 text-left text-lg font-medium text-gray-500 uppercase tracking-wider">Número de alerta</th>
                <th scope="col" class="px-6 py-3 text-left text-lg font-medium text-gray-500 uppercase tracking-wider">Tipo de anomalía</th>
                <th scope="col" class="px-6 py-3 text-left text-lg font-medium text-gray-500 uppercase tracking-wider">Índice de confiabilidad</th>
                <th scope="col" class="px-6 py-3 text-left text-lg font-medium text-gray-500 uppercase tracking-wider">Fecha de detección</th>
                <th scope="col" class="px-6 py-3 text-left text-lg font-medium text-gray-500 uppercase tracking-wider">Acción</th>
            </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
            {% for alerta in alertas_dict %}
            <tr class="bg-gray-200">
                <td class="px-6 py-4 whitespace-nowrap text-lg">{{ alerta.id }}</td>
                <td class="px-6 py-4 whitespace-nowrap flex items-center text-lg">
                    <svg class="w-5 h-5 text-white mr-2 bg-black" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M10 18a2 2 0 100-4 2 2 0 000 4zm-1-6V4a1 1 0 112 0v8a1 1 0 01-2 0z" clip-rule="evenodd"></path>
                    </svg>
                    {{ alerta.anomaly_type }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-lg">{{ alerta.confidence }}%</td>
                <td class="px-6 py-4 whitespace-nowrap text-lg">{{ alerta.timestamp|date:"Y-m-d H:i:s" }}</td> <!-- Formato de fecha -->
                <td class="text-lg">
                    {% if permissions.view_alert %}
                    <button 
                        type="button" 
                        class="bg-blue-500 text-white font-bold py-2 px-4 rounded"
                        onclick="openModal('{{ alerta.id }}', '{{ alerta.anomaly_type }}', '{{ alerta.confidence }}', '{{ alerta.timestamp }}', '{{ alerta.frame_image }}', '{{ alerta.created_by__username }}')"
                    >
                        Detalles
                    </button>
                    {% endif %}
                    {% if permissions.delete_alert %}
                    <form method="POST" action="{% url 'data_storage:eliminar_alerta' alerta.id %}" style="display:inline-block;">
                        {% csrf_token %}
                        <button type="submit" class="bg-red-500 text-white font-bold py-2 px-4 rounded mt-2">Eliminar</button>
                    </form>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5" class="px-6 py-4 whitespace-nowrap text-center text-gray-500 text-lg">No se encontraron alertas.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- Modal -->
<div id="myModal" class="fixed z-10 inset-0 overflow-y-auto hidden font-poppins bg-black bg-opacity-50">
    <div class="flex items-center justify-center min-h-screen px-4">
        <div class="bg-white p-6 rounded-lg shadow-lg w-104 h-auto m-5"> <!-- Modal más grande -->
            <div class="flex justify-between items-center border-b pb-3 mb-3">
                <h3 class="text-xl font-semibold text-gray-800 leading-tight">Detalles de la alerta</h3>
                <button class="text-gray-600 hover:text-gray-800 text-3xl transition duration-200" onclick="closeModal()">&times;</button>
            </div>
            <div class="space-y-4"> <!-- Espaciado más amplio -->
                <div class="flex justify-center">
                    <img id="modalImage" src="" class="w-72 h-72 object-cover rounded-lg shadow-md mb-4" alt="Imagen de la alerta"> <!-- Imagen más grande -->
                    <p id="noImageMessage" class="text-red-500 hidden text-center w-full">No hay imagen disponible.</p>
                </div>
                <p class="text-base text-gray-700"><strong class="font-bold text-gray-800">Número de alerta:</strong> <span id="modalId" class="text-gray-900"></span></p>
                <p class="text-base text-gray-700"><strong class="font-bold text-gray-800">Descripción de anomalía:</strong> <span id="modalType" class="text-gray-900"></span></p>
                <p class="text-base text-gray-700"><strong class="font-bold text-gray-800">Índice de confiabilidad:</strong> <span id="modalConfidence" class="text-gray-900"></span>%</p>
                <p class="text-base text-gray-700"><strong class="font-bold text-gray-800">Fecha de detección:</strong> <span id="modalTimestamp" class="text-gray-900"></span></p>
                <p class="text-base text-gray-700"><strong class="font-bold text-gray-800">Generado por el usuario:</strong> <span id="modalCreatedby" class="text-gray-900"></span></p>
            </div>
            <div class="mt-6 flex justify-end"> <!-- Espaciado mayor -->
                <button onclick="closeModal()" class="bg-blue-800 hover:bg-blue-700 text-white font-semibold py-3 px-6 rounded-md transition duration-300 shadow-lg">Cerrar</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}


{% block scripts %}
<script>
    function openModal(id, type, confidence, timestamp, frame_image, created_by){
        document.getElementById('modalId').innerText = id;
        document.getElementById('modalType').innerText = type;
        document.getElementById('modalConfidence').innerText = confidence;
        document.getElementById('modalTimestamp').innerText = timestamp;
        document.getElementById('modalCreatedby').innerText = created_by;

        const modalImage = document.getElementById('modalImage');
        const noImageMessage = document.getElementById('noImageMessage');
       

        if (frame_image) {
            modalImage.src = '/media/' + frame_image;  
            modalImage.classList.remove('hidden');
            noImageMessage.classList.add('hidden');
        } else {
            modalImage.classList.add('hidden');
            noImageMessage.classList.remove('hidden');
        }

        document.getElementById('myModal').classList.remove('hidden');
    }

    function closeModal() {
        document.getElementById('myModal').classList.add('hidden');
    }
</script>
{% endblock %}

data_storage/templates/data_storage/reports.html
{% extends 'core/base.html' %}
{% load static %}

{% block styles %}   
  <link href="{% static 'data_storage/css/tailwind.css' %}" rel="stylesheet"> 
  <link href="{% static 'data_storage/css/style.css' %}" rel="stylesheet"> 
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock %}

{% block title %}Reportes{% endblock %}

{% block content %}
<div class="border-1 border-gray-300 p-3 shadow-lg my-4">
    <div class="flex justify-between">
        <h1 class="text-3xl font-bold text-center leading-loose mx-4">Reportes</h1>
        <a href="{% url 'data_storage:main' %}">
            <button class="text-3xl font-medium text-center leading-loose mx-4 text-black hover:text-blue-500 transition duration-300">
                Ir a registro de alertas
            </button>
        </a>
    </div>
</div>

<div class="flex flex-col items-center">
    <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
            <tr>
                <th class="px-6 py-3 text-center text-xl font-medium text-gray-500 uppercase tracking-wider">Título</th>
                <th class="px-6 py-3 text-center text-xl font-medium text-gray-500 uppercase tracking-wider">Fecha de Generación</th>
                <th class="px-6 py-3 text-center text-xl font-medium text-gray-500 uppercase tracking-wider">Acción</th>
            </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
            {% for informe in informes %}
            <tr class="bg-gray-200">
                <td class="px-6 py-4 whitespace-nowrap flex items-center justify-center text-lg">
                    <i class="fa-3x fas fa-file-alt text-blue-500 mr-4"></i>
                    {{ informe.name }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-center text-lg">{{ informe.generated_at|date:"d M Y H:i" }}</td>
                <td class="px-6 py-4 whitespace-nowrap text-center text-lg">
                    <a href="{{ informe.pdf_file.url }}" target="_blank">
                        <button class="bg-blue-500 text-white font-bold py-2 px-4 rounded hover:bg-blue-600">
                            Descargar PDF
                        </button>
                    </a>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-center text-lg">
                    {% if permissions.delete_report %}
                    <a href="{% url 'data_storage:eliminar_reporte' informe.id %}" 
                       class="bg-red-500 text-white font-bold py-2 px-4 rounded hover:bg-red-600"
                       onclick="return confirm('¿Estás seguro de que deseas eliminar este reporte?')">
                        Eliminar
                    </a>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4" class="px-6 py-4 whitespace-nowrap text-center text-gray-500">No se encontraron informes.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="mt-4 my-6">
        <button class="text-xl bg-green-500 text-white font-bold py-4 px-4 rounded hover:bg-green-600" onclick="openFormModal()">
            Generar un reporte
        </button>
    </div>
</div>


<!-- Modal de generación de informe -->
<div id="formModal" class="fixed z-10 inset-0 overflow-y-auto hidden">
    <div class="flex items-center justify-center min-h-screen bg-black bg-opacity-50">
        <div class="bg-white p-6 rounded-lg shadow-lg w-1/3">
            <div class="fa-2x flex justify-between items-center">
                <h3 class="text-xl font-semibold ">Generar Informe</h3>
                <button class="text-gray-600" onclick="closeFormModal()">&times;</button>
            </div>
            <form method="POST" action="{% url 'data_storage:generar_informe' %}" target="_blank">
                {% csrf_token %}
                <div class="mt-4">
                    <div class=" my-2">
                        <em>Generar un reporte de un mes en específico</em>
                    </div>
                    <label for="mes" class="block text-sm font-medium text-gray-700">Mes</label>
                    <select name="mes" id="mes" class="mt-1 block w-full p-2 border border-gray-300 rounded-md">
                        <option value="1">Enero</option>
                        <option value="2">Febrero</option>
                        <option value="3">Marzo</option>
                        <option value="4">Abril</option>
                        <option value="5">Mayo</option>
                        <option value="6">Junio</option>
                        <option value="7">Julio</option>
                        <option value="8">Agosto</option>
                        <option value="9">Septiembre</option>
                        <option value="10">Octubre</option>
                        <option value="11">Noviembre</option>
                        <option value="12">Diciembre</option>
                    </select>
                </div>
                <div class="mt-4">
                    <label for="anio" class="block text-sm font-medium text-gray-700">Año</label>
                    <input type="number" name="anio" id="anio" min="2000" max="2100" required class="mt-1 block w-full p-2 border border-gray-300 rounded-md">
                </div>
                <div class="mt-6 flex justify-between">
                    <button type="submit" class="bg-blue-500 text-white font-bold py-2 px-4 rounded hover:bg-blue-600">
                        Generar PDF
                    </button>
                    <button type="button" class="bg-gray-400 text-white font-bold py-2 px-4 rounded hover:bg-gray-500" onclick="closeFormModal()">
                        Cancelar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}


{% block scripts %}
<script>
    function openFormModal() {
        document.getElementById('formModal').classList.remove('hidden');
    }

    function closeFormModal() {
        document.getElementById('formModal').classList.add('hidden');
    }
</script>
{% endblock %}